config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get 'about', to: 'pages#about'
  resources :articles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
    validates :title, presence: true, length: {minimum: 6, maximum: 100}
    validates :description, presence: true, length: {minimum: 10, maximum: 200}
end

app/models/user.rb
class User < ApplicationRecord
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
    before_action :set_article, only: [:show, :edit, :update, :destroy]

    def show
    end
    def index
        @articles = Article.all
    end
    def new
        @article = Article.new
    end
    def edit
    end
    def create
        @article = Article.new(article_params)
        if @article.save
            flash[:notice] = "Article was created successfully."
            redirect_to @article  
        else
            render 'new'
        end
    end
    def update
        if @article.update(article_params)
            flash[:notice] = "Article was updated successfully."
            # byebug
            redirect_to @article
        else
            render 'edit'
        end
    end
    def destroy
        @article.destroy
        redirect_to articles_path
    end

    private

    def set_article
        @article = Article.find(params[:id])
    end

    def article_params
        params.require(:article).permit(:title, :description)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def home   
    end
    def about
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/_form.html.erb
<%= render 'shared/errors' %>
<%= form_with(model: @article, local: true) do |f| %>
<center>
  <div class="container row justify-content-center background-cardheader p-4 shadow mb-5 rounded">
    <div class="mb-3 col-8">
      <%= f.label :title, class: 'form-label card-title' %>
      <%= f.text_field :title, class: 'form-control shadow', placeholder: "Title of article" %>
    </div>
    <div class="mb-3 col-8">
      <%= f.label :description, class: 'form-label card-title' %>
      <%= f.text_area :description, class: 'form-control shadow', placeholder: "Description of article" %>
    </div>
    <div class="col-8">
        <%= f.submit class: 'btn btn-outline-dark ' %>
    </div>
  </div>
</center>
<% end %>
<center>
  <%= link_to '[ Return to Articles Listing ]', articles_path, class: 'text-lighter' %>
</center>

app/views/articles/edit.html.erb
<div id="page-content">
    <center><h1 class="m-3">Edit Article</h1></center>

    <%= render 'form' %>
</div>

app/views/articles/index.html.erb
<div id="page-content">
  <center><h1 class="mt-3">Listing All Articles:</h1></center>

  <center>
  <% @articles.each do |article| %>
    <div class="row justify-content-md-center">
      <div class="col-8">
        <div class="card m-4 text-center shadow mb-5 bg-body rounded">
          <div class="card-header background-cardheader text-cardheader">
            by Abijah Ford.
          </div>
          <div class="card-body">
            <h5 class="card-title"><%= article.title %></h5>
            <p class="card-text"><%= truncate(article.description, length: 100) %></p>
            <%= link_to 'View', article_path(article), class: 'btn btn-outline-success' %>
            <%= link_to 'Edit', edit_article_path(article), class: 'btn btn-outline-info' %>
            <%= link_to 'Delete', article_path(article), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-outline-danger' %>
          </div>
          <div class="card-footer background-cardheader text-cardheader">
            <small>Created <%= time_ago_in_words(article.created_at) %> ago,
            edited <%= time_ago_in_words(article.updated_at) %> ago.</small>
          </div>
        </div>
      </div>
    </div>
  <% end %>
  <br>
  <center>
  <%= link_to 'Create New Article', new_article_path, class: 'btn btn-outline-dark' %>
  </center>
  <br>
</div>

app/views/articles/new.html.erb
<div id="page-content">
<center>
    <h1 class="m-3">Create a New Article</h1>
</center>
    <%= render 'form' %>
</div>

app/views/articles/show.html.erb
<div id="page-content">
<center><h1 class="m-3">Showing Article Details</h1></center>

<center>
<div class="container bg-light p-4 shadow rounded">
    <p><strong>Title: </strong><br><%= @article.title %></p>
    <p><strong>Description: </strong><br><%= @article.description %></p>
</div>
</center>
<br>
<center>
<%= link_to 'Edit', edit_article_path(@article), class: 'btn btn-outline-info' %>
<%= link_to 'Delete', article_path(@article), method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-outline-danger' %> <br><br>
<%= link_to '[ Return to Articles Listing ]', articles_path, class: 'text-lighter' %>
</center>
</div>

app/views/layouts/_footer.html.erb
<footer id="sticky-footer" class="py-4">
  <div class="container">
      <span>Copyright &copy; <%= link_to "Abijah Ford", "https://abijahford.info", class: "text-dark" %><span>
  </div>
</footer>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-success m-2 alert-dismissible fade show" role="alert">
    <%= msg %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to "ALPHA BLOG", root_path, class: "navbar-logo", id: "logo" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to "About", about_path, class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Articles
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link_to 'Create New Article', new_article_path, class: 'dropdown-item' %>
            <%= link_to 'View Articles', articles_path, class: 'dropdown-item' %>
          </ul>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Alpha-Blog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="d-flex flex-column">
    <%= render 'layouts/navbar' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<div id="page-content">
<center>
    <h1 class="m-3">About Page</h1>
</center>
<center>
    <%= link_to 'Articles Listing', articles_path, class: 'text-lighter' %>
    <%= link_to 'Home Page', root_path, class: 'text-lighter' %>
</center>
</div>

app/views/pages/home.html.erb
<div id="page-content">
    <div class="container" id="home-container">
        <div class="p-5 mb-4 text-center">
            <div class="container-fluid py-5">
                <h1 class="display-5 fw-bold text-light">Alpha Blog</h1>
                <p class="fs-4 text-light">Using a series of utilities, you can create this jumbotron, just like the one in previous versions of Bootstrap. Check out the examples below for how you can remix and restyle it to your liking.</p>
                <button class="btn btn-light btn-lg" type="button">Sign Up!</button>
            </div>
        </div>
    </div>
</div>

app/views/shared/_errors.html.erb
<% if @article.errors.any? %>
<div class="alert alert-danger m-2 alert-dismissible fade show" role="alert">
  <h2>The following errors prevented the article from being saved:</h2>
  <ul>
    <% @article.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>
<% end %>